name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cocotb pytest pytest-cocotb

    - name: Install Icarus Verilog
      run: sudo apt-get install -y iverilog

    - name: Run Cocotb tests
      run: |
        cd test
        make test

    - name: Publish test results
      uses: test-summary/action@v2.3
      with:
        paths: test/results.xml
